### ISSUE TITLE
Sliders and buttons showing values from other controls

### ISSUE THREAD

**Issue by thinium** [xot/ElectraOne#4]
Hello! I just made a custom Ableton Operator preset. Even though it controls the software correctly, the value text are displaying values from other controls. For example, a button that should show "FIXED" is displaying -6.3dB. A slider that should show 0.0 % is showing 100Hz. Many sliders are showing the raw values but not the formatted values from Ableton Live. 

How can I fix this? 

Here is a video showing what's happening
https://yes.hamoid.com/index.php/s/CsaDar6iRXn9NnZ

Here is the preset and Lua file:
[Archive.zip](https://github.com/xot/ElectraOne/files/14970285/Archive.zip)

Thank you!

**Comment by thinium** [comment]
I've found the issue: While I change the knob in my new Operator preset, it's still linked to the default Operator preset and use the same knob's reference number in the old preset (#16) instead of the new one (#67).

Here is another short video (84 seconds) explaining the issue:
https://yes.hamoid.com/index.php/s/FZb4YLmD4kLfdPd

In this example I am changing a slider with ref# 67, but in the log file it logs for example "Send value update 1/32 for control (16,0)". ref#16 is the "release" slider that shouldn't have received the update. So something is wrong with the reference parsing.
![Screenshot 2024-04-14 at 13 47 23](https://github.com/xot/ElectraOne/assets/1383198/f785080e-6a46-44fc-97dc-551e44addb3e)
![Screenshot 2024-04-14 at 13 47 55](https://github.com/xot/ElectraOne/assets/1383198/39325a80-cee4-487c-8764-103f87dbb547)

This is the default preset from you:
![Screenshot 2024-04-14 at 13 52 00](https://github.com/xot/ElectraOne/assets/1383198/81fffc2b-cf0b-4a21-a319-4ad3deff9aca)

Here is my log file:
[Log.txt](https://github.com/xot/ElectraOne/files/14970541/Log.txt)

I've deleted the default one from the hardware folder though (ctrlv2/presets/xot/ableton/). I don't understand why it's still linked to the old one
Thank you again!

**Comment by xot** [comment]
When changing the controlid and/or the MIDI CC parameter number (and associated device/MIDI channel), you should *also* update the ccmap. I suspect that in the Operator ccmap, the old controlid (#16) is still listed for "Repeat". That should be changed to #67.

**Comment by thinium** [comment]
I see! Thank you for the help! I did cut and paste many parameters but it seems all my control ids are changed. I wonder if re-ordering page also changes control-ids. I'll pay attention to that when I customise another preset
