### ISSUE TITLE
Create custom preset (dump not working)

### ISSUE THREAD

**Issue by Maus3rVonDutch** [xot/ElectraOne#5]
Hi, the documentation states you can customize a preset by a dump, is that supposed to work on Windows (Í'm seeing linux used in the config files)?

I'm talking about this section:

```
3. Load the device you want to create a preset for and select it; a blue hand should appear in it (and the preset that is constructed on the fly should appear on the E1).
4. This should create <devicename>.epr and <devicename>.ccmap in the dumps directory in the library folder (LIBDIR).
```

Also it was not apparent that `LIBDIR` is a config setting, so maybe you can update the documentation about that more clearly.
NB I've tried both forwared and backward slashes:

```
# Whether created patch info should be dumped (this is useful if you want
# to create your own custom patches for certain devices)
DUMP = True

# Whether to detect the E1 at start up (or assume it's there regardless)
DETECT_E1 = True
...
#
# If None, the remote script directory itself is tried.
LIBDIR = 'C:/Temp/Electra One'
```

I've also checked the remote script dir itself (even before i found and modified this LIBDIR config setting), I'm not seeing any .dump directory

**Comment by xot** [comment]
The `LIBDIR` config setting was confusing and has now been deprecated. Everything now happens within the install folder of the remote script, which is automatically detected at startup. Dumps should now appear in the `dumps` folder in the remote script dir (if `DUMP = True`). 

(Development actually takes place in MacOS).
