### ISSUE TITLE
preloading preset to E1 disk ignores CCMap

### ISSUE THREAD

**Issue by Maus3rVonDutch** [xot/ElectraOne#6]
Hi,

I successfully created a preset with a ccmap and a lua script for some conditional display. I need the ccmap not only for the ordering of the ableton config params, but also to define whether the midi should use 7bit or 14bit, and last but not least for configuring whether or not to use the Ableton display string of the config param (for instance "50%" or "22ms").

The documentation states u don't need to upload the ccmap to E1, only the `.epr` and `.lua` file, but then my preset is not working the same as when loading the preset from the `preloaded`  folder on Windows, which does have the ccmap besides the other files. 
What happens is, that when loading the preset from the E1 directly, it works but shows only the correct display string for controls that the "dump process" is able to figure out initially.

I have tried to both upload the ccmap to the E1, as well as to the preloaded folder (only ccmap, other files loaded from the E1), but it seems it is ignored in all cases. Only when I remove the preset from the E1, and then put all 3 files (. epr, .lua, .ccmap) back in the preloaded folder of the Windows file system, then  it behaves correctly again.

So my question is, why should a preset put directly on the E1 not need the ccmap? Currently it is not working as expected.

NB I also included the require call to the default script in my lua file (at the top) and I defined the defaultFormatter in the format field.

For reference I includes the files here.
[Eventide.zip](https://github.com/user-attachments/files/15904862/Eventide.zip)

(groeten uit Nijmegen trouwens ;))

**Comment by xot** [comment]
Thanks for raising this issue. Just checking: if you preload the InstantPhaserMkII .lua and .epr files to the E1 in the presets/xot/ableton folder on the E1, do you still keep a copy of InstantPhaserMkII.ccmap in the preloaded folder of the remote script? It needs to be in that folder because that's where the remote script can read from (it can't obtain it from the E1).

(Groeten uit Groningen, waar ik woon, Nijmegen is waar ik werk  ;-)

**Comment by xot** [comment]
Followup: you actually need to keep also the .epr and .lua file for any preset in the preloaded folder, even if you preload it onto the E1. The remote script uses these files as a backup in case something goes wrong recalling the preloaded preset. (Otherwise the remote script re-creates the .epr and ccmap using the "dump process". I will update the documentation

**Comment by Maus3rVonDutch** [comment]
Ok, thanks for clarifying, I thought I tested that scenario as well, but maybe not ;). I have preloaded the script to the E1 and also keeping the files in the preloaded folder of the midi remote scripts and it is showing the correct display strings as before.

NB I forgot to reply to my other ticket, about the dump not working, sorry for that, slipped my mind. I gues what happend there is I did modify the `config.py` to set the dump config setting, but I forgot the clear the pre-compiled `__pycache__` folder with the `config.pyc` so it was using a config file without the modification.

Lastly, thnx a lot for all your hard work, this is really great stuff. I'm a developer myself (.NET and web, not python or lua) and did some minor modifications on some SSL midi remote scripts to suit my needs. I know its not a light effort to figure things out without a clear api documentation (shame that Ableton does not provide one). Reverse engineering  how it all fits together (especially the hardcore Push code is hard to go through ;)) is not easy ,or at least it cost a considerable amount of time.

So thanks and keep it up!

**Comment by xot** [comment]
You're welcome. Two years ago I had an itch to scratch and that got this ball rolling. The remote script Python code written by Ableton for the  ontrol surfaces they support is an absolute nightmare (even though I think they actually tried to give it some structure). And the interface with Live is often broken (different parameters in a single device with the exact same name; many parameters MIDI mappable within Live itself but inaccessible to the remote script; to name but a few).

**Comment by Maus3rVonDutch** [comment]
Ai, sounds terrible, even more respect, thnx man!
